local M = {
  variants = {
    dark = 'dark',
    light = 'light',
    dawn = 'dawn',
    iris = 'iris',
    black = 'black',
    ['black-zen'] = 'black-zen',
    ['dark-vitesse'] = 'dark-vitesse',
    ['light-vitesse'] = 'light-vitesse',
    space = 'space',
  },

  groups = {
    background = 'bg',
    foreground = 'fg',
    cursor = 'cursor',
    selection = 'selection',
    line = 'line',
    gutter = 'gutter',
    gutterActive = 'gutterActive',
    comment = 'comment',
    keyword = 'keyword',
    string = 'string',
    number = 'number',
    constant = 'constant',
    func = 'function',
    type = 'type',
    variable = 'variable',
    class = 'class',
    operator = 'operator',
    error = 'error',
    warning = 'warning',
    info = 'info',
    accent = 'accent',
    match = 'match',
    menu = 'menu',
    menuSelection = 'menuSelection',
    border = 'border',
    commentBg = 'commentBg',
  },
}

return M
